import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';
import { useEffect } from 'react';
import { getUserFromLocalCookie } from '../lib/auth';
import Navbar from './Navbar';


const Layout = ({children}) => {
  const [isUserAuthorized, setIsUserAuthorized]  = useState(false);
  // const router = useRouter();
  // useEffect(() => {
  //   authCheck();

  //   // on route change start - hide page content by setting authorized to false  
  //   const hideContent = () => setIsUserAuthorized(false);
  //   router.events.on('routeChangeStart', hideContent);

  //   // on route change complete - run auth check 
  //   router.events.on('routeChangeComplete', authCheck)

  //   // unsubscribe from events in useEffect return function
  //   return () => {
  //       router.events.off('routeChangeStart', hideContent);
  //       router.events.off('routeChangeComplete', authCheck);
  //   }
  // }, [])
  // const authCheck = () => {
  //   const user = getUserFromLocalCookie();
  //   console.log({userjnjdn: user})
  //   setIsUserAuthorized(true);
  //   if(user) {
  //     if(router.pathname==='/auth/login' || router.pathname==='/auth/signup') {
  //       router.push('/');
  //     }
  //   } 
  //   else {
  //     if(router.pathname==='/write') {
  //       setIsUserAuthorized(false)
  //       router.push('/auth/login');
  //     }
  //   }
  // }
  return(
    <>
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>

      <Navbar />
      <main>
        <div>
          {children}
        </div>
      </main>
    </>
  )
}
export default Layout;
