import { ApolloClient, InMemoryCache } from '@apollo/client';
import { Grid } from '@mui/material';
import axios from 'axios';
import { isNullableType } from 'graphql';
import Head from 'next/head'
import Image from 'next/image'
import { parseCookies } from 'nookies';
import { useEffect } from 'react';
import Banner from '../components/Banner';
import BlogCard from '../components/BlogCard';
import Navbar from '../components/Navbar'
import GET_ALL_BLOGS from '../graphql/queries/getAllBlogs';
import styles from '../styles/Home.module.css'
// import router from 'next/router'

export default function Home({blogs}) {
  // console.log();
  const arr = [1,2,3,4];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>
      <main>
        <Navbar />
        <div style={{marginTop: 100, marginLeft: 35, marginRight: 10}}>
          {/* <Banner /> */}
          <Grid container>
            {
              blogs.map(blog => {
                return(
                  <Grid item lg={4} md={6} sm={12}>
                    <BlogCard blog={blog}/>
                  </Grid>
                )
              })
            }
          </Grid>
        </div>
      </main>
    </div>
  )
}

export const getServerSideProps = async (ctx) => {
  const res = await axios.get(`http://localhost:1337/api/blogposts/`);
  return {
    props: {
      blogs: res.data.data,
    },
  };
};

// export const getServerSideProps = async (ctx) => {
//   const res = await axios.get(`http://localhost:1337/api/blogposts/`);
  
//   let jwt = null;
//   jwt = parseCookies(ctx).jwt;

//   return {
//     props: { 
//       blogs: res.data.data,
//       jwt: jwt
//     }
//   };
// };