import { Grid } from '@mui/material';
import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner';
import BlogCard from '../components/BlogCard';
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  const user = false;
  const arr = [1,2,3,4];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link key={1} rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@600&display=swap" rel="stylesheet"/>
        <link key={2} href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@1,300&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"></link>
      </Head>
      <main>
        <Navbar />
        <div style={{marginTop: 100, marginLeft: 35, marginRight: 10}}>
          {/* <Banner /> */}
          <Grid container>
            
              {
                arr.map(ele => {
                  return(
                    <Grid item lg={4} md={6} sm={12}>
                      <BlogCard />
                    </Grid>
                  )
                })
              }
              
            
          </Grid>
        </div>
        
      </main>
      
    </div>
  )
}
